# Form implementation generated from reading ui file 'YTMultiDownloader_3.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainUi:

    def __init__(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(990, 648)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(size_policy)
        main_window.setMinimumSize(QtCore.QSize(990, 648))
        main_window.setMaximumSize(QtCore.QSize(990, 648))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("yt.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        main_window.setWindowIcon(icon)
        main_window.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.folder_btn = QtWidgets.QPushButton(self.central_widget)
        self.folder_btn.setGeometry(QtCore.QRect(770, 80, 180, 60))
        self.folder_btn.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(175, 0, 0);\n"
                                      "    border: 1px solid #000000;\n"
                                      "    border-radius: 30;\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    font: 75 14pt \"Leelawadee UI\";\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: rgb(135, 0, 0);\n"
                                      "}")
        self.folder_btn.setIconSize(QtCore.QSize(16, 16))
        self.folder_btn.setObjectName("folder_btn")
        self.download_btn = QtWidgets.QPushButton(self.central_widget)
        self.download_btn.setGeometry(QtCore.QRect(400, 540, 191, 60))
        self.download_btn.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(175, 0, 0);\n"
                                        "    border: 1px solid #000000;\n"
                                        "    border-radius: 30;\n"
                                        "    color: rgb(255, 255, 255);\n"
                                        "    font: 75 14pt \"Leelawadee UI\";\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: rgb(135, 0, 0);\n"
                                        "}")
        self.download_btn.setIconSize(QtCore.QSize(16, 16))
        self.download_btn.setObjectName("download_btn")
        self.folder_opt = QtWidgets.QLineEdit(self.central_widget)
        self.folder_opt.setGeometry(QtCore.QRect(40, 80, 681, 60))
        self.folder_opt.setStyleSheet("background-color: rgb(175, 0, 0);\n"
                                      "border: 1px solid #000000;\n"
                                      "border-radius: 30;\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "font: 75 14pt \"Leelawadee UI\";")
        self.folder_opt.setReadOnly(True)
        self.folder_opt.setPlaceholderText("")
        self.folder_opt.setObjectName("folder_opt")
        self.layoutWidget = QtWidgets.QWidget(self.central_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 190, 911, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontal_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.youtube_urls = QtWidgets.QTextEdit(self.layoutWidget)
        self.youtube_urls.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: 75 14pt \"Leelawadee UI\";\n"
                                        "border: 1px solid #000000;\n"
                                        "border-radius: 15;\n"
                                        "background-color: rgb(175, 0, 0);")
        self.youtube_urls.setObjectName("youtube_urls")
        self.horizontal_layout.addWidget(self.youtube_urls)
        spacer_item = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontal_layout.addItem(spacer_item)
        self.youtube_opt = QtWidgets.QTextEdit(self.layoutWidget)
        self.youtube_opt.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "font: 75 14pt \"Leelawadee UI\";\n"
                                       "border: 1px solid #000000;\n"
                                       "border-radius: 15;\n"
                                       "background-color: rgb(175, 0, 0);")
        self.youtube_opt.setReadOnly(True)
        self.youtube_opt.setObjectName("youtube_opt")
        self.horizontal_layout.addWidget(self.youtube_opt)
        main_window.setCentralWidget(self.central_widget)

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "YouTubeMultiDownloader"))
        self.folder_btn.setToolTip(_translate("main_window", "<html><head/><body><p>Folder to download all "
                                                             "files.</p></body></html>"))
        self.folder_btn.setWhatsThis(_translate("main_window", "<html><head/><body><p><br/></p></body></html>"))
        self.folder_btn.setText(_translate("main_window", "Select folder"))
        self.download_btn.setToolTip(_translate("main_window", "<html><head/><body><p>Button to start download "
                                                               "files.</p></body></html>"))
        self.download_btn.setWhatsThis(_translate("main_window", "<html><head/><body><p><br/></p></body></html>"))
        self.download_btn.setText(_translate("main_window", "Download"))
        self.youtube_urls.setToolTip(_translate("main_window", "<html><head/><body><p><span style=\" "
                                                               "font-size:12pt;\">Paste youtube links "
                                                               "here!</span></p></body></html>"))
        self.youtube_urls.setPlaceholderText(_translate("main_window", "Paste youtube links here..."))
        self.youtube_opt.setToolTip(_translate("main_window", "<html><head/><body><p><br/></p></body></html>"))
        self.youtube_opt.setWhatsThis(_translate("main_window", "<html><head/><body><p><br/></p></body></html>"))
